### ISSUE TITLE
Delete the related users/volunteers when an organization or a site is deleted

### ISSUE THREAD

**Issue by shubhpatel108** [systers/language-translation#101]
Presently, deleting an organization throws ForeignKeyViolation error (and rollbacks). This is because even after the organization is deleted, there are references to it from the user table. 

When a site is deleted, the user-role association is deleted. The actual volunteer user still persists with permissions to login.

**Comment by arkokoley** [comment]
Is this issue a good place to start, if I want to contribute to this project as a part of GSoC 2017?

I have a fair knowledge of Rails and its intricacies.
