### ISSUE TITLE
Longer words flow out of the text box

### ISSUE THREAD

**Issue by shubhpatel108** [systers/language-translation#103]
Many 'show' pages display the text without hyphenating the longer words. 
<img width="541" alt="screen shot 2016-02-09 at 1 00 42 am" src="https://cloud.githubusercontent.com/assets/4345133/12896547/955fcbde-cec8-11e5-9580-91adc09197e2.png">

**Comment by ujithaperera** [comment]
character overflow issue is no longer appearing in Articles. But it is nice to fill these line gaps in same colour other than the keeping white

**Comment by ujithaperera** [comment]
![screen shot 2016-03-03 at 4 05 42 pm](https://cloud.githubusercontent.com/assets/12997101/13491711/e2c8d21e-e159-11e5-89be-45618149ed8b.png)
