### ISSUE TITLE
User attributes' validations are not set.

### ISSUE THREAD

**Issue by ishit** [systers/language-translation#113]
The lengths of these attributes are not capped:
- Username
- Email 
- First name and last name

![screenshot from 2016-03-08 17 14 19](https://cloud.githubusercontent.com/assets/4801132/13600812/7f3e78ec-e551-11e5-9b60-6681ba5c9ecb.png)

**Comment by prachikumari** [comment]
I am working on this issue. What should I keep as maximum length of fields, as of now I am keeping the length constraints as 20 for all.

**Comment by shubhpatel108** [comment]
@prachikumari Let's not put any constraint on email. Rest can be of 10 characters. You might also want to add content validation on them. They should only contain alphanumeric characters.

**Comment by prachikumari** [comment]
I have created a fix, but it is failing the CI jobs.  Please verify the changes. This is the link of the patch
https://github.com/prachikumari/language-translation/commit/04551be2bbd42dcac3296cf4429e6829aa06799c

**Comment by adityathiru** [comment]
Hi! I'm a GSoC 2017 aspirant. 
I'd like to know if this issue is fixed, or should I work on it ?

**Comment by Rupinderwadali** [comment]
@adityathiru wait for the mentor's reply or meanwhile you can check the pull requests. But wait until the mentor assigned you some task or review the task. You can join the systers slack channels for more information and queries.

**Comment by adityathiru** [comment]
Sure! Will do :+1: 
Thanks!
