### ISSUE TITLE
No Contribution guidelines

### ISSUE THREAD

**Issue by fatimarafiqui** [systers/language-translation#146]
There are no contribution guidelines that I could find in the documentation. @Rupinderwadali I see many open issues and pull requests. How can one start contributing? Please help me out.

**Comment by fatimarafiqui** [comment]
@Rupinderwadali @rosariorobinson Any updates on this?

**Comment by Rupinderwadali** [comment]
@fatimarafiqui, You can start contribution from the open issues and can also open a new issue if you find any. Code of the pull request is not reviewed yet so it is not merged. Let me know if you find any difficulty.
Thanks for your interest.

**Comment by fatimarafiqui** [comment]
@Rupinderwadali I think rules for contribution can be added to the documentation, like it is done in other systers repositories. 
Example Reference Link: https://github.com/systers/macc/blob/develop/docs/Contribution.md

**Comment by Rupinderwadali** [comment]
Basic rules are similar for almost all the projects like mentioned in the above docs. You are not supposed to resolve the issue that is assigned to other student or wait until the mentor assigns you some tasks. You can join systers slack channel for more information and queries. Mentors list will be updated soon 
Thanks for your interest. Please go through the issues list and also add new issue that you find any.
