### ISSUE TITLE
Aditya prioritizes issues that are open.

### ISSUE THREAD

**Issue by MeepyMay** [systers/language-translation#162]
## Description
As a contributor,
I want to code with the most recent up to date repo,
so that I don't repeat any previous codes. 

## Mocks
N/A

## Acceptance Criteria
- Issues are clearly marked with **1 Priority Label**.

## Definition of Done
- Passes acceptance criteria items.

## Estimation
- 0.5 Hours

**Comment by adityathiru** [comment]
* Prioritised all issues with a Priority Label.
* Also added a tag (if necessary) which indicates, if the issue is a bug or enhancement or a question.
