### ISSUE TITLE
Aditya writes Weekly Status Report for Week 1 and Bio Information.

### ISSUE THREAD

**Issue by MeepyMay** [systers/language-translation#164]
## Description
As an Admin,
I want to regularly check Aditya's progress throughout the GSoC program,
so that I can help where needed. 

## Mocks
N/A

## Acceptance Criteria
- All sections in [Aditya's wiki](https://github.com/systers/language-translation/wiki/30-May-~-21-August) marked with "TBD" have content.

## Definition of Done
- Passes acceptance criteria items.

## Estimation
- 0.5 Hours

**Comment by adityathiru** [comment]
* Updated Bio Information
* All sections with TBD are completed and up to date for week 1 and 2.
