### ISSUE TITLE
will_paginate or kaminari?

### ISSUE THREAD

**Issue by wonook** [systers/language-translation#17]
I have taken a look at both of their GitHub repos, and I'm concerned that `will_paginate` isn't being maintained at the time. You can take a look at them yourself: [will_paginate](https://github.com/mislav/will_paginate), [kaminari](https://github.com/amatsuda/kaminari).
`will_paginate` has 59 open issues and 33 pending PRs, whereas `kaminari` has 13 of each. Also, `will_paginated` had been committed almost an year ago now, whereas `kaminari` has been committed only about a week ago. I think there should be some reconsiderations about using the `will_paginate` gem.

**Comment by isuriupeksha** [comment]
Both gem are working fine. Seems now `kaminaari` is doing great. You can update the gem.

**Comment by rosariorobinson** [comment]
Let's be careful that we are using gems that are regularly being maintained. We had this issue on another project and cause much havoc on coding and change configuration. Let's continue to think about long term and not just what we can do right now.

**Comment by wonook** [comment]
@isuriupeksha 
You're the one who have implemented things with it, so I think you will be the one who knows better where it was used. I think it would be more safe if you could replace it.

**Comment by wonook** [comment]
@isuriupeksha 
Will you have a look into this issue?
