### ISSUE TITLE
Set up JSON API for Rails

### ISSUE THREAD

**Issue by wonook** [systers/language-translation#20]
We'll have to separate out Rails and ReactJS in the future, and use Rails as our JSON API.
Applying [rails-api](https://github.com/rails-api/rails-api) would make Rails more lightweight.

**Comment by isuriupeksha** [comment]
We don't need to separate application `API` using that gem. We can simply integrate  `API` using ActiveModel::Serializers and authenticate HTTP Basic Authentication system. 
I have already working on `API` integrate because it is in my this week schedule.
