### ISSUE TITLE
CanCan, CanCanCan or Pundit?

### ISSUE THREAD

**Issue by wonook** [systers/language-translation#29]
A simple discussion about the CanCan gem. It had been originally used by @SaumyaGurtu last year, but as you can see at its [github repo](https://github.com/ryanb/cancan), CanCan hadn't been maintained for almost two years now, and it's been showing some problems with Rails 4 as well (Rails 5 is on the way, so clearing up these kinds of problems seems to be needed).
Now, as an alternative to CanCan, a maintained version of cancan, [CanCanCan](https://github.com/CanCanCommunity/cancancan) and [Pundit](https://github.com/elabs/pundit) exist to replace the gem. There's also a possible option to do everything manually using the [Rolify](https://github.com/RolifyCommunity/rolify) gem.
@SaumyaGurtu I would like to know if there had been any specific reason for using CanCan instead of these two alternatives last year. It seems like CanCanCan existed since January 2014, and Pundit had been out for a while.
I am also open to other opinions about the issue as well.

**Comment by isuriupeksha** [comment]
We can go with `CanCanCan` gem.

**Comment by wonook** [comment]
It seems as the optimal solution for now, since it enables us to make full use of CanCan without changing the syntaxes, etc. too much. I'll collect the mentors' opinions and apply the changes soon.
