### ISSUE TITLE
Errors due to change in role -> role_id

### ISSUE THREAD

**Issue by wonook** [systers/language-translation#32]
Due to @isuriupeksha's change in role -> role_id in the users, the seed files do not work anymore.

**Comment by wonook** [comment]
Seeding files, signing up are some problems that I detected so far.

**Comment by isuriupeksha** [comment]
@wonook let me check and post a fix.

**Comment by wonook** [comment]
I guess I'll just get rid of the `role` column from the `user` model. Roles are supposed to be attached between a user and the organization the user belongs to, so this won't be a problem anymore I guess. Still, later when you post something be just a little more careful about these side-effects.
