### ISSUE TITLE
How the Posts & Sites works in PLT app?

### ISSUE THREAD

**Issue by isuriupeksha** [systers/language-translation#35]
PLT app already have `Posts` and `Sites` section implemented. But `Posts` has a associated with `User` model. Therefore in the `User` new or edit form, it named as `Location` select box. 

`Sites` also the same. It is associated with the `Posts` model only. So can you simply describe, that how it work in the app?

**Comment by wonook** [comment]
I think `Posts==Installations` and it's the terms used by Peace Corps members to indicate the teams or groups in particular countries (e.g. Chuukese Post in Micronesia) and `Sites` are places or the teams that the `Post` has control over (e.g. Site1 in the Chuukese Post). I think `Organizations` are going to be nation-wise, (e.g. Micronesia).
Well this was as far as I could understand from the previous documents and the application itself. I don't get why `Post` has contact details (email, number) on it though.

**Comment by wonook** [comment]
@rosariorobinson @SaumyaGurtu Please leave a reply on the thread!

**Comment by rosariorobinson** [comment]
1. Posts = country

2. I believe we wanted to use sites as a dedicated site within a post/country. For example, Kenya post could have 2 sites, Nairobi and Mombasa. 

3. orgs = other organizations. (We thought peace corps is one organization that could potentially use this app. There could be other orgs peace corps partners or outside of peace corps, for example USAID, Red cross. This is an open source application where the concept of open that anyone can use it.

**Comment by wonook** [comment]
Thanks for the answer! I see how it works now.
