### ISSUE TITLE
Activity stream for article

### ISSUE THREAD

**Issue by isuriupeksha** [systers/language-translation#36]
I would like to add "Article activity stream" new feature to the app. This may help to keep record a log. And we can make sure who is the responsible for update, create and delete `Articles`. 

Welcome your suggestions!

**Comment by abelards** [comment]
Looks nice and in the current trend of apps.
I'll let Systers tell us if that's a useful feature people would actually use or not.

If we choose to go for it, it's pretty easy to log who created or updated things.
Logging deletions is a bit harder, not technically but as a UX choice: you'd have a "deleted" list?

**Comment by rosariorobinson** [comment]
Great feature. We need to keep track of what users do in the app. An assumption that is often made, but glad we're discussing it here and something we need to be sure we are doing across all projects. 

Yes please implement.

**Comment by isuriupeksha** [comment]
@rosariorobinson  Thanks your feedback,
 
@abelards Yes, we cannot include deleted records activities once articles has bee deleted. But I mean,  article may have many audio or videos files attached into one article. So at the moment media files has been deleted, we can include audio and videos deletion on activity list.

**Comment by abelards** [comment]
OK nice to know, thanks!

On a side-note, I think there are gems to replace "deletion" with a "to the
trashbox"-like feature.
A few years ago that was called `acts_as_paranoid` I guess.
If you go down that road it's very interesting (and has nice UX challenges)

BUT I'm definitely NOT telling you to try!
That's significant work and you might have higher priorities.
See with Rose if she'd like it, or mark it as a "nice to have" near the end
of the summer if you have time :)

Cheers,


On Tue, Jun 30, 2015 at 10:11 AM, Isuri Upeksha <notifications@github.com>
wrote:

> @rosariorobinson <https://github.com/rosariorobinson> Thanks your
> feedback,
>
> @abelards <https://github.com/abelards> Yes, we cannot include deleted
> records activities once articles has bee deleted. But I mean, article may
> have many audio or videos files attached into one article. So at the moment
> media files has been deleted, we can include audio and videos deletion on
> activity list.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/systers/language-translation/issues/36#issuecomment-117050778>
> .
>



-- 
Sylvain Abélard
"J’ai décidé d’être heureux, c’est meilleur pour la santé." - Voltaire
"Il faudrait essayer d’être heureux, ne serait-ce que pour donner
l’exemple." - Prévert

**Comment by MeepyMay** [comment]
@adityathiru @prachi1210 @Anjali05 

I think there was a misunderstanding for GSoC17. Deletion, Creating, Updating, etc. should all be shown on the activity list as well as the person responsible. 

@adityathiru has closed the issue since it's already there.
