### ISSUE TITLE
Manage single article versioning - new feature implementation 

### ISSUE THREAD

**Issue by isuriupeksha** [systers/language-translation#37]
When many users update articles, it may happen mistakes. So I would like to introduce article revisions management feature to the article section. 

There is a gem name `paper_trail` (https://github.com/airblade/paper_trail) to enable versioning. 

Welcome your suggestions!

**Comment by wonook** [comment]
Hmm, I think this can be an optional feature.
I don't think there will be a lot of revisions on the articles once the pictures and the languages are there.

**Comment by isuriupeksha** [comment]
yes. this doesn't need to implement.
