### ISSUE TITLE
Article's state transitions

### ISSUE THREAD

**Issue by isuriupeksha** [systers/language-translation#39]
Once members posting articles, it should go through verifying process. 

1. All posted article in `draft` state by users.
2. Then editor or admin do translating language. At the moment, user can change the article state to `reviewing` state. 
3. It everything is fine, we can change articles to `publish` state. 

By adding this feature, members know that what are the published and unpublished articles. 
We can use AASM gem https://github.com/aasm/aasm

Welcome your suggestions!

**Comment by abelards** [comment]
That'd be nice but perhaps complicated. It's very nice to learn and practice though :)

**Comment by SaumyaGurtu** [comment]
Make sure that you make a new proper documentation of new features and
changes for gsoc 2015. This should be done side by side because later you
might forget the workflow of features. @wonook @isuri

**Comment by rosariorobinson** [comment]
Please see my comments on #38 about staying focused on your user audience. 

@wonook @isuriupeksha

**Comment by wonook** [comment]
I think having a column of `bool` deciding whether it's published or not would be enough for this. It'll make it much easier to implement.

**Comment by abelards** [comment]
I find when we want a `bool` we usually want a timestamp instead, like
`published_at`.
As easy to code, and people often like the extra info: users to know when
it was done,
and when things go wrong for devs to analyse and fix things in the console
:)
Cheers,

On Thu, Jun 25, 2015 at 7:18 PM, Won Wook SONG <notifications@github.com>
wrote:

> I think having a column of bool deciding whether it's published or not
> would be enough for this. It'll make it much easier to implement.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/systers/language-translation/issues/39#issuecomment-115328462>
> .
>



-- 
Sylvain Abélard
"J’ai décidé d’être heureux, c’est meilleur pour la santé." - Voltaire
"Il faudrait essayer d’être heureux, ne serait-ce que pour donner
l’exemple." - Prévert

**Comment by wonook** [comment]
That's a better idea!

**Comment by isuriupeksha** [comment]
Thanks for the feedback. 

I am going to implement `published_at` feature to the article section. `Admin` & `Volunteer` can accept articles. But all the articles which created by contributors goes to `published_at` false.
