### ISSUE TITLE
Add  gem `rack-mini-profiler` for development

### ISSUE THREAD

**Issue by isuriupeksha** [systers/language-translation#47]
Profiler for your development Ruby rack apps. I think, that displays speed badge for every HTML page

**Comment by wonook** [comment]
The gem seems like it's for checking speed for the application, but I'm not sure if this will be really mandatory

**Comment by isuriupeksha** [comment]
This for only development env. Not production. We can check number of SQL queries which app does at one request. This is great tool if you optimize the app speed.

**Comment by isuriupeksha** [comment]
We can use this gem when we optimize the SQL queries. So I am closing this ticket now.
