### ISSUE TITLE
Remove volunteers_controller.rb and contributors_controller.rb files from controller 

### ISSUE THREAD

**Issue by isuriupeksha** [systers/language-translation#50]
It is enough to manage members by `users_controller.rb`. So we can remove following two files. 

-- `volunteers_controller.rb`
-- `contributors_controller.rb`

**Comment by abelards** [comment]
Beware of removing anything if you haven't made a script to migrate data.
Also don't assign things to me for the next two weeks because I'll be on vacation until the 26th ^^
Cheers,

**Comment by wonook** [comment]
I'm already doing that in #42. No worries.
