### ISSUE TITLE
Rename Installation model to Country

### ISSUE THREAD

**Issue by wonook** [systers/language-translation#58]
This had been causing some confusion for us. `Installation`s are referred as `Post`s in all of the views. However, `Posts` can be misleading since it can have meanings like 'posts' in as blog 'posts'. So to clear this out a little bit, I'm thinking of maybe changing its naming into something like 'Nation' or 'Country', since according to #35, 'Posts' have meanings that actually refer to 'Countries'.

As for the naming in the DB table, `Installation` model's `installation` column should be renamed as `name` to keep consistency as well.

Seed files should be filled up with proper examples as well, as we now have an answer on #35 .

**Comment by wonook** [comment]
Also, instead of having email, address, and contact columns on the `Installation` model, I think choosing a user as a 'post manager' would be more convenient. We won't have to write things twice then.

**Comment by isuriupeksha** [comment]
Yes. It is great if we can change `Installation` name.
