### ISSUE TITLE
Thinking about the need of the Annotate gem

### ISSUE THREAD

**Issue by wonook** [systers/language-translation#59]
I noticed that @isuriupeksha added the `annotate` gem a while ago, but I'm quite unclear about its necessity. It only gets updated manually and it is often forgotten on updates, and it often causes merge conflicts as well. However, above all, we also have a copy of a file that describes exactly what it's trying to do already in `db/schema.rb` which is maintained automatically upon migrations, so I'm quite unsure about why we need the gem in our application.

**Comment by wonook** [comment]
I suggest taking this one out. Any opinions @isuriupeksha ?

**Comment by isuriupeksha** [comment]
don't remove that. I am using that for development.

**Comment by wonook** [comment]
I'm not sure so I'm asking, but does this do anything more than the `db/schema.rb` file?

**Comment by isuriupeksha** [comment]
Yes. for me it is very easy to check table attributes.

**Comment by wonook** [comment]
I see. It's completely of no use to me so I was just wondering. If you want to keep using it, you probably would have to keep an eye on it for yourself, to keep it up-to-date since I'll probably forget to update it upon manipulating the schema.
