### ISSUE TITLE
Resizing Photos upon uploads + Thumbnails

### ISSUE THREAD

**Issue by wonook** [systers/language-translation#62]
The images being uploaded are always being uploaded without being resized and thus are creating some inconsistency among the pictures. Some resizing can be easily done through `CarrierWave`, which is our tool for uploading images. 
Also, it would be better if we could have thumbnails on the index page. These thumbnails can be easily made using `MiniMagick`, which is a tool widely used for various applications for creating thumbnails.

**Comment by isuriupeksha** [comment]
The images sizes will be change once I integrated new design. So better to update once they are ready.

**Comment by wonook** [comment]
Alright, sounds cool to me.

**Comment by shubhpatel108** [comment]
This seems to be implemented and commented out in `picture_uploader.rb`. Why don't we start using images of different sizes? As pointed out by @wonook, the index page should use the thumbnails. 
Is anyone already working on this?

**Comment by abelards** [comment]
Not yet but you're welcome to assign yourself on the issue and start PRing ;)

**Comment by shubhpatel108** [comment]
Thanks @abelards, I'm on this one!

**Comment by shubhpatel108** [comment]
Along with creating thumbnail version, shall we create another version for show and edit page of an article?
Presently the original image is used directly without modification. A 1024 × 768 pixels or a larger image can consume lot of user's network.

**Comment by abelards** [comment]
I'd love that, if @rosariorobinson has pointers for you to choose the right
size :)
I suppose we'd have to:
- trim down for list (thumbnails)
- trim down for show/edit (pic) if image too big
- not try to resize if the image is below a certain size (say, show-size
and below)

Cheers,


On Mon, Jan 25, 2016 at 10:31 AM, Shubham Patel <notifications@github.com>
wrote:

> Along with creating thumbnail version, shall we create another version for
> show and edit page of an article?
> Presently the original image is used directly without modification. A 1024
> × 768 pixels or a larger image can consume lot of user's network.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/systers/language-translation/issues/62#issuecomment-174447606>
> .
>



-- 
Sylvain Abélard
"J’ai décidé d’être heureux, c’est meilleur pour la santé." - Voltaire
"Il faudrait essayer d’être heureux, ne serait-ce que pour donner
l’exemple." - Prévert

**Comment by isuriupeksha** [comment]
Hi @shubhpatel108 and @abelards, 
There are different version of images. This web application support to mobile screens as well. Here you can get images sizes. https://github.com/systers/language-translation/issues/23

Note: We haven't completed the articles new templates into the app. We have to integrate new article grid views.
