### ISSUE TITLE
Member New/Invitation feature

### ISSUE THREAD

**Issue by isuriupeksha** [systers/language-translation#75]
Following features are included. 
1. Admin can create new user or create user without invitation email 
2. Admin can invite new user with welcome email message.

**Comment by isuriupeksha** [comment]
@wonook What is the default role when user sign up from directly site? and I don't see it create user roles with signup process completed.

**Comment by wonook** [comment]
Currently, the user isn't granted any kind of role upon signing up. As you can see in [`ability.rb`](https://github.com/systers/language-translation/blob/develop/app/models/ability.rb), the newly signed-up users fall into 'else' and thus can only `read` the `Articles`. Users can be granted other roles through the `Members Show` view or the `Sites Show` view for now.
