### ISSUE TITLE
Admin user cannot create new Site record. 

### ISSUE THREAD

**Issue by isuriupeksha** [systers/language-translation#78]
@wonook due to Ability setup, cannot create new Site record. 
`      can :manage, Site,
          installation_id: @user.organization.installations.map { |a| a.id }
`

**Comment by isuriupeksha** [comment]
It need to add like this.

`can :new, Site`
`can :manage, Site, installation_id: @user.organization.installations.map { |a| a.id }`

**Comment by isuriupeksha** [comment]
@wonook Admin cannot access to `Organization` page to create or modify organizations. Is something missing in `Ability` class?

**Comment by isuriupeksha** [comment]
Since I need to apply new templates to organization. I updated the `Ability` class as follows, 
`can :manage, [Language, Category, Article, Organization]`

**Comment by wonook** [comment]
@isuriupeksha 
Do you see a case where an admin of a specific organization will have to manage other organizations? I don't think that a 'Peace Corps' admin should be able to manage the 'Red Cross' organization.
A `superadmin` can manage the organizations through the ActiveAdmin interface at `http://localhost:3000/admin`

**Comment by wonook** [comment]
I've also checked, but I was able to create `sites` that belonged to the `installations` of the `organization` that the user belonged to. Are you sure that this doesn't works? It works just fine for me.

**Comment by wonook** [comment]
I'll give a fix for the bug.

**Comment by wonook** [comment]
@isuriupeksha Check out the PR and leave a comment for me. #79
