### ISSUE TITLE
Make develop branch as the default branch for this repository

### ISSUE THREAD

**Issue by wonook** [systers/language-translation#8]
I think it would be good to make the staging branch as a default branch (which is currently just a copy of the master branch), so that we can keep the master branch separate, and make the staging branch as our "development branch" before we check if the application works correctly.

We'll have to send pull requests for each issues to the staging branch from our issue-related branches.

@isuriupeksha and I would have to work together, so making a branch like this seems suitable.

**Comment by rosariorobinson** [comment]
Actually, to keep consistency with other repos, I've added develop.  Please use this instead. Thanks.

**Comment by rosariorobinson** [comment]
I'm also going to setup Travis CI for this repo. Please give me until the end of the week, 5 June 2015.

**Comment by wonook** [comment]
Got it. I'll remove the staging branch.
I've opened an issue about CI #15 , I believe that discussions about Travis can be done there!

**Comment by wonook** [comment]
@rosariorobinson I think it would be more convenient if you could make the `develop` branch as our default branch of this repository at the repository settings, since we'll be making our pull requests there!

**Comment by rosariorobinson** [comment]
I think we're all set on this issue. Develop branch default and travis ci set up.

**Comment by wonook** [comment]
:+1:  Awesome.
