### ISSUE TITLE
Fixing the folder structure

### ISSUE THREAD

**Issue by wonook** [systers/language-translation#9]
We'll have to take things out of the `PLTCode` directory into our repository's root directory.

**Comment by wonook** [comment]
@isuriupeksha , I think I've already done this on the other branch, but would it be fine with the work that you have already done? I'm worried about the merge conflicts. 
Probably it would be better if we could review and merge your work before I can re-do this.

**Comment by isuriupeksha** [comment]
Ok, I will move the directory. Currently I am working some updates. I will send a merge request tomorrow.

**Comment by wonook** [comment]
Yeah. Be sure to clean out your commits a bit and divide up the pull requests so that we can review things in adequate chunks.

**Comment by wonook** [comment]
@isuriupeksha you shouldn't really copy&paste stuff from others' branches..
By the way, for us to cooperate, you should really organize things up a little bit, so that it is review-able..
Be sure to send `Pull Requests` that are related to some `issues` in adequate chunks, not in huge piles of commits.

**Comment by isuriupeksha** [comment]
@wonook What you mean `copy&paste`? I push my changes to remote branch. And I have been developed many features in my list.

**Comment by wonook** [comment]
nvm take a look at the comments on the PR. I'll merge it once the comments are applied.
