### ISSUE TITLE
Alert close button not working

### ISSUE THREAD

**Issue by shubhpatel108** [systers/language-translation#98]
<img width="1050" alt="screen shot 2016-01-28 at 12 11 20 pm" src="https://cloud.githubusercontent.com/assets/4345133/12637061/5583cf1a-c5b8-11e5-85e7-50231db5386c.png">

The cross provided on right top corner for closing the alert message is not working. Such error messages are used on all forms.

**Comment by ujithaperera** [comment]
This issue is also remain in forgot password feature. top-right close button is not working 
![screen shot 2016-03-03 at 4 14 40 pm](https://cloud.githubusercontent.com/assets/12997101/13492071/f93ce60a-e15b-11e5-9aba-bce529be43d5.png)
